
# project configuration
project_id = "obgazoojckeyylmzgjlo"

[storage]
[storage.course-materials]
public = true
allowed_mime_types = ["application/pdf", "application/msword", "application/vnd.openxmlformats-officedocument.wordprocessingml.document", "image/jpeg", "image/png"]
file_size_limit = "50MB"

