
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://obgazoojckeyylmzgjlo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9iZ2F6b29qY2tleXlsbXpnamxvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNDM5MDQsImV4cCI6MjA2MDkxOTkwNH0.T55X2ZR9WHF-SWpiKQhbFs8-JLm8DTDQDZI0huWVC0I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
